# write a probram to ccreate a dictionary of hindi 
# words with values as their engish translations provide user with an option
# to look up a word

words = {
    "namaste": "hello",
    "dost": "friend",
    "paani": "water",
    "pustak": "book",
    "madad": "help",
"shukriya": "thank you",
"kalam": "pen",
    "mez": "table",
    "roti": "bread",
    "doodh": "milk",
    "pankha": "fan",
    "kapda": "cloth",
    "dost": "friend",
    "khana": "food",
    "khana": "food",
    "andar": "inside",
    "kal": "tomorrow",
    "kal": "tomorrow",
    "bitta_kal": "yesterday",
    "aadmi": "man",
    "ladka": "boy",
    "ladki": "girl",
    "nadi": "river",
    "pahad": "mountain",
    "gharana": "family",
    "bazar": "market",
    "bazaar": "market",
    "gaadi": "vehicle",
    "sadak": "road",
    "school": "school",
    "shahar": "city",
    "gaon": "village",
    "mandir": "temple",
    "masjid": "mosque",
    "path": "lesson",
    "khidki": "window",
    "darwaza": "door",
    "charpai": "cot",
    "kursi": "chair",
    "kamra": "room",
    "dariya": "sea",
    "phool": "flower",
    "ped": "tree",
    "patta": "leaf",
    "dharti": "earth",
    "suraj": "sun",
    "chand": "moon",
    "taara": "star",
    "aag": "fire",
    "hawa": "air",
    "mitti": "soil",
    "pathar": "stone",
    "rail": "train",
    "naukri": "job",
    "paisa": "money",
    "kela": "banana",
    "aam": "mango",
    "angoor": "grapes",
    "papita": "papaya",
    "gajar": "carrot",
    "tamatar": "tomato",
    "pyaz": "onion",
    "adrak": "ginger",
    "lehsun": "garlic",
    "namak": "salt",
    "chini": "sugar",
    "haldi": "turmeric",
    "mirch": "chilli",
    "daliya": "porridge",
    "billi": "cat",
    "kutta": "dog",
    "ghoda": "horse",
    "gai": "cow",
    "bhains": "buffalo",
    "machhli": "fish",
    "pakshi": "bird",
    "kabutar": "pigeon",
    "mor": "peacock",
    "haathi": "elephant",
    "bhalu": "bear",
    "sher": "lion",
    "bagh": "tiger",
    "hath": "hand",
    "pair": "foot",
    "aankh": "eye",
    "naak": "nose",
    "kaal": "time",
    "gussa": "anger",
    "khushi": "happiness",
    "dukhi": "sad",
    "bhookh": "hunger",
    "pyaas": "thirst",
    "safed": "white",
    "kala": "black",
    "neela": "blue",
    "laal": "red",
    "peela": "yellow",
    "hara": "green",
    "zindagi": "life",
    "mohabbat": "love",
}
words_input = input("welcome ayush hindi and english dictionary:",)
print("the meaning of your word is:", words.get(words_input, "word not procesing in dictionary"))

# 2 question = input eight number from user and display all the unique numbers
s=[]

